import Image from "next/image";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: " Privacy Policy - Paphos Sea Cruises",
  description: "Privacy Policy for Paphos Sea Cruises",
  keywords: "Privacy Policy, Paphos Sea Cruises, data protection, GDPR",
  authors: [{ name: "Paphos Sea Cruises" }],
}

export default function PrivacyPolicy() {
  return (
    <div className="">
      <div className="relative h-[450px] ">
        <Image
          src="/backgrounds/blue.jpg"
          alt="Blue wave background"
          fill
          className=""
          priority
        />

        {/* Tours Title */}
        <div className="absolute inset-0 flex items-center justify-start px-8 sm:px-16 md:px-24 lg:px-32">
          <h1 className="text-white text-4xl md:text-6xl font-sans font-bold">
            Privacy Policy
          </h1>
        </div>
      </div>

      <div className="px-4 max-w-7xl font-sans mx-auto pb-12">
        <p className=" text-gray-500 mt-4">
          Effective date: March 25, 2024
        </p>

        <p className="mt-4 text-gray-500 ">
          Paphos Sea Cruises (“us”, “we”, or “our”) collect, use, and share
          information in connection with your use of our website
          paphosseacruises.com and services (collectively, the “Services”).
        </p>

        <p className="text-gray-500 mt-4">
          This page informs you of our policies regarding the collection, use,
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
        </p>

        <p className="text-gray-500 mt-4">
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, terms used in this Privacy Policy have the same meanings as in
          our Terms and Conditions, accessible from paphosseacruises.com
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Definitions</h2>

        <h3 className="text-xl font-medium mt-4">Services</h3>
        <p className="text-gray-500 mt-4">
          Services provided through our website paphosseacruises operated by
          Paphos Sea Cruises.
        </p>

        <h3 className="text-xl font-medium mt-4">Personal Data</h3>
        <p className="text-gray-500 mt-4">
          Personal Data means data about a living individual who can be
          identified from those data (or from those and other information either
          in our possession or likely to come into our possession).
        </p>

        <h3 className="text-xl font-medium mt-4">Usage Data</h3>
        <p className="text-gray-500 mt-4">
          Usage Data is data collected automatically either generated by the use
          of the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).
        </p>

        <h3 className="text-xl font-medium mt-4">Cookies</h3>
        <p className="text-gray-500 mt-4">
          Cookies are small pieces of data stored on your device (computer or
          mobile device).
        </p>

        <h3 className="text-xl font-medium mt-4">Data Controller</h3>
        <p className="text-gray-500 mt-4">
          Data Controller means the natural or legal person who (either alone or
          jointly or in common with other persons) determines the purposes for
          which and the manner in which any personal information are, or are to
          be, processed.
        </p>
        <p className="text-gray-500 mt-4">
          For the purpose of this Privacy Policy, we are a Data Controller of
          your Personal Data.
        </p>

        <h3 className="text-xl font-medium mt-4">
          Data Processors (or Service Providers)
        </h3>
        <p className="text-gray-500 mt-4">
          Data Processor (or Service Provider) means any natural or legal person
          who processes the data on behalf of the Data Controller.
        </p>
        <p className="text-gray-500 mt-4">
          We may use the services of various Service Providers in order to
          process your data more effectively.
        </p>

        <h3 className="text-xl font-medium mt-4">Data Subject (or User)</h3>
        <p className="text-gray-500 mt-4">
          Data Subject is any living individual who is using our Service and is
          the subject of Personal Data.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-2">
          Information Collection And Use
        </h2>

        <p className="text-gray-500 mt-4">
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>

        <h3 className="text-xl font-medium mt-4">Types of Data Collected</h3>
        <h4 className="text-lg font-semibold mt-2">Personal Data</h4>
        <p className="text-gray-500 mt-4">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Cookies and Usage Data</li>
        </ul>
        <p className="text-gray-500 mt-4">
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or
          instructions provided in any email we send.
        </p>

        <h4 className="text-lg font-semibold mt-4">Usage Data</h4>
        <p className="text-gray-500 mt-4">
          We may also collect information how the Service is accessed and used
          (“Usage Data”). This Usage Data may include information such as your
          computer’s Internet Protocol address (e.g. IP address), browser type,
          browser version, the pages of our Service that you visit, the time and
          date of your visit, the time spent on those pages, unique device
          identifiers and other diagnostic data.
        </p>

        <h4 className="text-lg font-semibold mt-4">Location Data</h4>
        <p className="text-gray-500 mt-4">
          We may use and store information about your location if you give us
          permission to do so (“Location Data”). We use this data to provide
          features of our Service, to improve and customize our Service.
        </p>
        <p className="text-gray-500 mt-4">
          You can enable or disable location services when you use our Service
          at any time, through your device settings.
        </p>

        <h4 className="text-lg font-semibold mt-4">Tracking & Cookies Data</h4>
        <p className="text-gray-500 mt-4">
          We use cookies and similar tracking technologies to track the activity
          on our Service and hold certain information.
        </p>

        <p className="text-gray-500 mt-4">
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags, and scripts to collect and track
          information and to improve and analyze our Service.
        </p>

        <p className="text-gray-500 mt-4">
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>

        <p className="text-gray-500 mt-4">Examples of Cookies we use:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-gray-500 mt-4">
            Session Cookies: We use Session Cookies to operate
            our Service.
          </li>
          <li className="text-gray-500 mt-4">
            Preference Cookies:We use Preference Cookies to
            remember your preferences and various settings.
          </li>
          <li className="text-gray-500 mt-4">
            Security Cookies: We use Security Cookies for
            security purposes.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-2">Use of Data</h2>
      <p className="text-gray-500 mt-4">Paphos Sea Cruises uses the collected data for various purposes:</p>
      <ul className="list-disc ml-6 mb-4 text-gray-500 mt-4">
        <li >To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
        <li>To provide customer support</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
      </ul>

      <h2  className="text-2xl font-semibold mt-6 mb-2">Legal Basis for Processing Personal Data Under GDPR</h2>
      <p className="text-gray-500 mt-4">If you are from the European Economic Area (EEA), Paphos Sea Cruises legal basis for collecting and using personal information depends on the context and type of data collected.</p>
      <p className="text-gray-500 mt-4">We may process your Personal Data because:</p>
      <ul className="list-disc ml-6 text-gray-500 mt-4 mb-4">
        <li>We need to perform a contract with you</li>
        <li>You have given us permission</li>
        <li>It is in our legitimate interests and not overridden by your rights</li>
        <li>For payment processing purposes</li>
        <li>To comply with the law</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Retention of Data</h2>
      <p className="text-gray-500 mt-4">We retain Personal Data only as long as necessary for the purposes in this policy. This includes complying with legal obligations, resolving disputes, and enforcing policies. Usage Data is typically retained for shorter periods unless required for security or legal reasons.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Transfer Of Data</h2>
      <p className="text-gray-500 mt-4">Your information may be transferred to — and maintained on — servers outside your jurisdiction. Your consent to this policy represents your agreement to such transfers. We take all necessary steps to ensure data is treated securely and in accordance with this policy.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Disclosure Of Data</h2>
      <p className="text-gray-500 mt-4"><strong>Disclosure for Law Enforcement:</strong> We may disclose your Personal Data when required by law or public authorities.</p>
      <p className="text-gray-500 mt-4"><strong>Legal Requirements:</strong> Disclosure may be made to:</p>
      <ul className="list-disc ml-6 mb-4 text-gray-500 mt-4">
        <li>Comply with legal obligations</li>
        <li>Protect rights or property of Paphos Sea Cruises</li>
        <li>Prevent wrongdoing related to the Service</li>
        <li>Protect personal safety of users or the public</li>
        <li>Defend against legal liability</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Security Of Data</h2>
      <p className="text-gray-500 mt-4">We use commercially acceptable means to protect your data but cannot guarantee absolute security.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">“Do Not Track” Signals</h2>
      <p className="text-gray-500 mt-4">We do not support Do Not Track. You can enable or disable it via your browser settings.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Your Data Protection Rights Under GDPR</h2>
      <p className="text-gray-500 mt-4">If you are in the EEA, you have rights to access, correct, delete, restrict or object to processing of your data, request portability, or withdraw consent. Contact us to exercise these rights. Identity verification may be required. You may also complain to your local Data Protection Authority.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Service Providers</h2>
      <p className="text-gray-500 mt-4">We may use third parties to provide or analyze our Service. They only access your data to perform tasks on our behalf under confidentiality agreements.</p>
      <p className="text-gray-500 mt-4">Paphos Sea Cruises complies with GDPR obligations as a processor and offers a Data Privacy Addendum (DPA) upon request via info@paphosseacruises.com.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Analytics</h2>
      <p className="text-gray-500 mt-4">We use Google Analytics to monitor site traffic. You can opt-out by installing the browser add-on. More info: <a href="http://www.google.com/intl/en/policies/privacy/" className="text-blue-600 underline">Google Privacy & Terms</a></p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Payments</h2>
      <p className="text-gray-500 mt-4">For paid services, we use third-party processors like PayPal. We do not store card details. PayPals Privacy Policy: <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" className="text-blue-600 underline">View Policy</a></p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Links To Other Sites</h2>
      <p className="text-gray-500 mt-4">We may link to external sites. We advise reviewing their privacy policies as we are not responsible for their practices.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Childrens Privacy</h2>
      <p className="text-gray-500 mt-4">We do not knowingly collect data from anyone under 18. If we become aware of such collection, we will delete the data.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Changes To This Privacy Policy</h2>
      <p className="text-gray-500 mt-4">We may update this policy and will notify users via email and/or Service notices. Please review this policy periodically.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">Contact Us</h2>
      <p className="text-gray-500 mt-4">If you have questions about this Privacy Policy, contact us at <a href="mailto:info@paphosseacruises.com" className="text-blue-600 underline">info@paphosseacruises.com</a></p>

      </div>
    </div>
  );
}
